### ISSUE TITLE
Precision Estimation for undirected models with known structure

### ISSUE THREAD

**Issue by ostwalprasad** [skggm/skggm#125]
Hello!

For models with known structures, adjacency matrix can be used to deliberately make precision zero wherever there is no edge. Is this possible with skggm? I could not find relevant functions.

There's an algorithm for the same in:   _The Elements of Statistical Learning
Book by Jerome H. Friedman, Robert Tibshirani, and Trevor Hastie_ - **Algorithm 17.1** or also in _Whittaker (1990)_

Thank you!

**Comment by mnarayan** [comment]
Yes, this can be done by specifying a matrix of regularization values for the parameter `lam` where when the presence of an edge is known, the corresponding regularization value is set to 0 and otherwise the regularization value is set to some large constant (usually larger than the largest entry of the sample covariance matrix). 

To see how this would work you can look at the `AdaptiveGraphicalLasso` estimator which has the option to use a binary matrix for adaptive regularization [(see here)](https://github.com/skggm/skggm/blob/develop/inverse_covariance/adaptive_graph_lasso.py#L35). This particular implementation amounts to performing the relaxed lasso which creates an initial estimate of the inverse covariance using the regular graphical lasso and then refits the graphical lasso using the zero/non-zero pattern from the initial estimate.

You can directly provide a pre-specified binary weight matrix for regularization as done [here](https://github.com/skggm/skggm/blob/develop/inverse_covariance/adaptive_graph_lasso.py#L104) using the `lam` parameter for the GraphicalLasso estimators.

**Comment by ostwalprasad** [comment]
Thanks for detailed answer.

I followed through and was able to generate zero precisions by passing pre-specified weight matrix to `lam` parameter of `QuicGraphicalLasso`.
